name: build

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:

jobs:
  # See https://github.com/mvdan/github-actions-golang
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [oldstable, stable]
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-expanding-configurations
        include:
          - os: windows-latest
            go-version: 1.22.x
          - os: macos-latest
            go-version: 1.22.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go install moq
        run: go install

      - name: Run vet
        if: matrix.os == 'ubuntu-latest'
        run: go vet ./...

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Test
        run: go test ./...
